bio: >
    Antonis F. Lentzakis is a Postdoctoral Research Associate at the Future Urban Mobility IRG, part of Singapore-MIT Alliance for Research and Technology (SMART/FM). His current research focuses on the extension and enhancement of DynaMIT2.0, a system that employs simulation-based Dynamic Traffic Assignment (DTA), for traffic estimation, prediction, and control, developed by the MIT Intelligent Transportation Systems Lab. He holds a PhD in Electrical and Electronic Engineering from Nanyang Technological University, a MSc in Operations Research and Production Engineering & Management from the Technical University of Crete.

bio_image: imgs/me-new.jpg

position: Postdoctoral Research Associate at SMART/FM

blurb: Interested in autonomous systems, traffic modeling, management and simulation

projects:
    - name: Density-based Clustering for Tolling Zone Definition
      links:
        - link: https://www.sciencedirect.com/science/article/abs/pii/S0968090X20306008?dgcid=author
          title: Trans. Res. Part C 2020
          type: pub
        - link: https://www.researchgate.net/publication/343532602_Feature-variant_clustering_methods_for_tolling_zone_definition_and_their_impact_on_distance-based_toll_optimization
          title: TRB 2020
          type: pub
      image: imgs/BCBCD_network.png

    - name: Region-based Urban Traffic Management
      links:
        - link: https://ieeexplore.ieee.org/abstract/document/8917309
          title: ITSC 2019
          type: pub
          link: https://www.sciencedirect.com/science/article/abs/pii/S0968090X18300068
          title: Trans. Res. Part C 2018
          type: pub
        - link: https://dr.ntu.edu.sg/bitstream/10356/75886/1/G1103343B%20Antonios%20Lentzakis%20PhD%20Thesis.pdf
          title: PhD Thesis
          type: pub
      image: imgs/region-based.png

    - name: NTU-NXP Smart Mobility Test Bed
      links:
        - link: https://www.youtube.com/watch?v=tRP420yvqD0
          title: Speed-profile dependent shortest path algorithm Demo
          type: video
      image: imgs/ntu-nxp.png

    - name: RENAISSANCE
      links:
        - link: http://artemis.library.tuc.gr/MT2009-0060/MT2009-0060.pdf
          title: Master Thesis
          type: pub
      image: imgs/renaissance.jpg

    - name: Work zone management
      links:
        - link: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.631.7902&rep=rep1&type=pdf
          title: TRB 2008
          type: pub
        - link: https://www.sciencedirect.com/science/article/abs/pii/S0968090X07000873
          title: Trans. Res. Part C 2008
          type: pub
      image: imgs/work-zone.png

    # - title: >
    #     Generating safe trajectories in dynamic environments by leveraging
    #     information about obstacle motion
    #   links:
    #     - link: /publications/st-andrews-thesis.pdf
    #       title: Undergraduate Thesis
    #   image: imgs/dodger.png
    #   name: Dodger
